### ISSUE TITLE
書かかせて → 書かせて

### ISSUE THREAD

**Issue by eggplants** [tonkotsuboy/zenn-articles#61]
https://github.com/tonkotsuboy/zenn-articles/blob/5bd34e757ae5b39420a1132ff06b23b89451ab44/articles/devin-for-test.md?plain=1#L2

**Comment by tonkotsuboy** [comment]
ひえーありがとうございます！
fixしました。
https://github.com/tonkotsuboy/zenn-articles/commit/55c856db4940cc0ab32a557bf0f6f552ceca736c
